# Generated by Django 3.2.13 on 2022-05-30 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Rate',
        ),
    ]
