# Generated by Django 3.2.13 on 2022-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mid_rate',
            field=models.FloatField(default=0),
        ),
    ]
