# Generated by Django 3.2.13 on 2022-06-03 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0004_auto_20220603_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
